### ISSUE TITLE
Routing Multiple Operation

### ISSUE THREAD

**Issue by Zephyria77** [OmniaSolutions/odooAddons#5]
Il modulo consente di inserire un "default supplier" per una determinata operazione all'interno della routing e questa è una gran cosa. Nel caso di operazioni multiple (interne ed esterne) il workorder viene generato solamente come produzione esterna. In molti casi i prodotti subiscono lavorazioni interne prima di essere spediti ad un fornitore per una specifica lavorazione (o anche più lavorazioni esterne con diversi fornitori)
Sarebbe comodo poter generare i workorder ed in base alla sequenza di operazioni stabilite nella routing, creare i picking di produzione esterna, quindi che il wh/out, contenesse il prodotto allo stadio di lavorazione precedente per poi rientrare e passare all'operazione successiva (che può essere un'altra lavorazione esterna)

**Comment by OmniaGit** [comment]
gia funziona cosi.
puoi decidere per ogni fase a chi mandare la lavorazione in modo manuale.
